// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: '<%=props['i18nDefault'] || (props['i18nLanguages'] && props['i18nLanguages'][0])%>',
  supportedLanguages: [<%- (props['i18nLanguages'] || []).map( lang => `'${lang}'`).join(', ') %>]
};
